# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20161117_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
