# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('playlist_file', models.CharField(blank=True, max_length=100)),
                ('playback_start_at', models.IntegerField(default=0)),
                ('length', models.CharField(blank=True, max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('response_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoint.VideoResponse')),
            ],
        ),
    ]
