# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresponse',
            name='original_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videoresponse',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
